// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbbcixkekoqoukzzdkxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYmNpeGtla29xb3Vrenpka3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDEyMDksImV4cCI6MjA3MTYxNzIwOX0.jKW2TsYIoy1AESvc4asswwurWn0RX9fTAMWTAP6s9bA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});